package com.fullstack.demo;

import com.fullstack.demo.exception.CourseNotFoundException;
import com.fullstack.demo.model.Course;
import com.fullstack.demo.repository.CourseRepository;
import com.fullstack.demo.repository.InMemoryCourseRepository;
import com.fullstack.demo.service.CourseService;

public class ExceptionPractice {
    public static void main(String[] args) {
        
        // --- TASK A: Set up CourseService ---
        CourseRepository courseRepository = new InMemoryCourseRepository();
        CourseService courseService = new CourseService(courseRepository);

        // --- TASK B: Add two courses ---
        // (Using the 4-item constructor we verified in Assignment 01)
        try {
            Course course1 = new Course("C001", "Java Fundamentals", 14, "Beginner");
            Course course2 = new Course("C002", "React Frontend Development", 21, "Intermediate");
            
            courseService.createCourse(course1);
            courseService.createCourse(course2);
        } catch (Exception e) {
            System.out.println("Setup Error: " + e.getMessage());
        }

        // --- TASK C: Find an existing course ---
        System.out.println("=== Find Existing Course (C001) ===");
        try {
            Course course = courseService.getCourseById("C001");
            course.printSummary();
        } catch (CourseNotFoundException e) {
            System.out.println("Error: " + e.getMessage());
        }

        // --- TASK D: Find a missing course and catch the exception ---
        System.out.println("\n=== Find Missing Course (C999) ===");
        try {
            Course missingCourse = courseService.getCourseById("C999");
            
            // This line will NEVER run because the line above throws the exception!
            missingCourse.printSummary(); 
            
        } catch (CourseNotFoundException e) {
            // We catch the error safely and print the message generated by the Service Layer
            System.out.println("Friendly message for user: " + e.getMessage());
        }

        // --- TASK E: Add one more try/catch block ---
        System.out.println("\n=== Find Missing Course (C888) ===");
        try {
            courseService.getCourseById("C888");
        } catch (CourseNotFoundException e) {
            // Here, we ignore the Service message completely and write our own custom message
            System.out.println("Cannot display course details because the course does not exist.");
        }
    }
}